user_names : tuple = ('PeTeR', 'jOhN', 'mArY', 'pAuL', 'AnNa', 'JoY', 'PaMellA', 'jOhN')
count.res = user_names.count('jOhN')
print(user_names)
user_names = tuple(name for name in user_names if name.__contains__('a'))
print(user_names)
user_names = tuple(name for name in user_names if name.startswith('P'))
print(user_names)
name_len = tuple(len(name) for name in user_names)
print(name_len)